import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Character, GetCharacterResults } from "../types";

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <>
    <div className={styles.bar}>
      <p className={styles.titleBar}>Products</p>
    </div>
    <div className={styles.container}>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by list products" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {characters.map((character) => {
        return (
          <div key={character.id} className={styles.card}>
              <div className={styles.image}>
                <Image
                  loader={imageLoader}
                  src={character.image}
                  alt={character.name}
                  width="200.65"
                  height="123.61"
                />
                </div>
                
                  <div className={styles.label}>{character.name}</div>
                  <div className={styles.label}>{character.brand}</div>
                  <h3 className={styles.value}>R$ {character.price}</h3>
          </div>
        );
      })}
    </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("http://localhost:8080/products");
  const results : GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
